apiVersion: v1
kind: ConfigMap
metadata:
  name: database-params
data:
  DB_HOST: "postgresql"
  DB_NAME: "petclinic"
  DB_USER: "user"
  DB_PASS: "pass"
  DB_PORT: '5432'
  DB_URL: jdbc:postgresql://postgresql/petclinic
