apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: demo-pipeline
spec:
  params:
    - default: 'https://github.com/kforetas/spring-petclinic.git'
      description: アプリのソースコードリポジトリ
      name: repo-url
      type: string
    - default: rhnconsultingkemori
      description: docker hub username
      name: docker-username
      type: string
    - default: 'https://github.com/kforetas/petclinic-gitops.git'
      description: マニフェスト管理用リポジトリ
      name: manifest-repo-url
      type: string
    - default: latest
      description: ビルドするイメージのタグ
      name: image-tag
      type: string
  tasks:
    - name: git-clone-source
      params:
        - name: SUBDIRECTORY
          value: source
        - name: DELETE_EXISTING
          value: 'true'
        - name: URL
          value: $(params.repo-url)
        - name: REVISION
          value: main
        - name: DEPTH
          value: '1'
      taskRef:
        params:
          - name: kind
            value: task
          - name: name
            value: git-clone
          - name: namespace
            value: openshift-pipelines
        resolver: cluster
      workspaces:
        - name: output
          workspace: shared-data
    - name: maven-test
      runAfter:
        - git-clone-source
      workspaces:
        - name: source
          workspace: shared-data
      taskSpec:
        workspaces:
          - name: source
        steps:
          - name: run-test
            image: registry.access.redhat.com/ubi9/openjdk-17:1.18
            script: |
              #!/bin/sh
              cd $(workspaces.source.path)/source
              # テストだけを実行するコマンド
              ./mvnw test
    - name: build-and-push
      params:
        - name: IMAGE
          value: 'docker.io/$(params.docker-username)/petclinic:$(params.image-tag)'
        - name: DOCKERFILE
          value: ./Dockerfile
        - name: CONTEXT
          value: source/source
        - name: STORAGE_DRIVER
          value: vfs
      runAfter:
        - maven-test
      taskRef:
        params:
          - name: kind
            value: task
          - name: name
            value: buildah
          - name: namespace
            value: openshift-pipelines
        resolver: cluster
      workspaces:
        - name: source
          workspace: shared-data
  workspaces:
    - name: shared-data
