apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: demo-pipeline
spec:
  params:
    - default: 'https://github.com/kforetas/spring-petclinic.git'
      description: アプリのソースコードリポジトリ
      name: repo-url
      type: string
    - default: rhnconsultingkemori
      description: docker hub username
      name: docker-username
      type: string
    - default: 'https://github.com/kforetas/petclinic-gitops.git'
      description: マニフェスト管理用リポジトリ
      name: manifest-repo-url
      type: string
    - default: latest
      description: ビルドするイメージのタグ
      name: image-tag
      type: string
  tasks:
    - name: git-clone-source
      params:
        - name: SUBDIRECTORY
          value: source
        - name: DELETE_EXISTING
          value: 'true'
        - name: URL
          value: $(params.repo-url)
        - name: REVISION
          value: main
        - name: DEPTH
          value: '1'
      taskRef:
        params:
          - name: kind
            value: task
          - name: name
            value: git-clone
          - name: namespace
            value: openshift-pipelines
        resolver: cluster
      workspaces:
        - name: output
          workspace: shared-data
    - name: maven-test
      runAfter:
        - git-clone-source
      workspaces:
        - name: source
          workspace: shared-data
      taskSpec:
        workspaces:
          - name: source
        steps:
          - name: run-test
            image: registry.access.redhat.com/ubi9/openjdk-17:1.18
            script: |
              #!/bin/sh
              cd $(workspaces.source.path)/source
              mvn test
    - name: build-and-push
      params:
        - name: IMAGE
          value: 'docker.io/$(params.docker-username)/petclinic:$(params.image-tag)'
        - name: DOCKERFILE
          value: ./Dockerfile
        - name: CONTEXT
          value: source
        - name: STORAGE_DRIVER
          value: vfs
      runAfter:
        - maven-test
      taskRef:
        params:
          - name: kind
            value: task
          - name: name
            value: buildah
          - name: namespace
            value: openshift-pipelines
        resolver: cluster
      workspaces:
        - name: source
          workspace: shared-data
    - name: git-clone-manifest
      params:
        - name: SUBDIRECTORY
          value: manifest
        - name: DELETE_EXISTING
          value: 'false'
        - name: URL
          value: $(params.manifest-repo-url)
        - name: REVISION
          value: main
        - name: DEPTH
          value: '1'
      taskRef:
        params:
          - name: kind
            value: task
          - name: name
            value: git-clone
          - name: namespace
            value: openshift-pipelines
        resolver: cluster
      workspaces:
        - name: output
          workspace: shared-data
    - name: update-gitops
      params:
        - name: DELETE_EXISTING
          value: 'false'
        - name: GIT_USER_NAME
          value: kforetas
        - name: GIT_USER_EMAIL
          value: kforetxp@yahoo.co.jp
        - name: GIT_SCRIPT
          value: |-
            # 1. 開発環境（dev）のディレクトリへ移動 
            cd $(workspaces.source.path)/manifest/manifest/app
            TARGET_DIR="overlays/dev"
            cd $TARGET_DIR
            # 2. kustomization.yaml 内の newTag の行だけを置換 
            sed -i "s|newTag:.*|newTag: $(params.image-tag)|g" kustomization.yaml
            # 3. Git Push 
            git add . 
            git commit -m "Update dev image to $(params.image-tag)" 
            git push origin HEAD:main
      runAfter:
        - build-and-push
        - git-clone-manifest
      taskRef:
        params:
          - name: kind
            value: task
          - name: name
            value: git-cli
          - name: namespace
            value: openshift-pipelines
        resolver: cluster
      workspaces:
        - name: source
          workspace: shared-data
  workspaces:
    - name: shared-data
