apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: deploy-db-dev
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: 'https://github.com/kforetas/petclinic-gitops'
    targetRevision: HEAD
    path: manifest/db/overlays/dev
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: petclinic-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
