resources:
  - ../../base

# Commit sync - commit_hash_tag
images:
  - name: docker.io/rhnconsultingkemori/petclinic
    newName: docker.io/rhnconsultingkemori/petclinic
    newTag: f680c7580e218c9b9ca57a1b4deafa805ae0fe62
