resources:
  - ../../base

# Commit sync - commit_hash_tag
images:
  - name: docker.io/rhnconsultingkemori/petclinic
    newName: docker.io/rhnconsultingkemori/petclinic
    newTag: 9fef52c6e3c371a7990449f6153eef0a0641cd22
